name = "kory-fp-matsuri-2026-materials"
version = "0.1.0"
defaultTargets = ["KoryFPMatsuri2026Materials"]

[[lean_lib]]
name = "KoryFPMatsuri2026Materials"
roots = ["Root"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
