/-
M-types as a quotient: the type of *all* pointed coalgebras ("unfoldings"),
quotiented by bisimilarity.

I (@kory33) think this construction follows the idea described in
the paper by Gylterud et al. (https://arxiv.org/abs/2001.06696), which in turn
refers to the work of Aczel and Mendler (https://doi.org/10.1007/BFb0018361),
but I have not verified the correspondence in detail. The Agda formalization of
Gylterud et al. is at https://github.com/niccoloveltri/aczel-mendler, and it seems to define
the weakly terminal coalgebra as a union of all (unpointed) coalgebras, so
there's already a difference in the definition of the carrier (I am not certain how essential this is).

Contrast with Mathlib's `PFunctor.M` (ω-limit of approximations) and
`QPF.Cofix` (quotient of `PFunctor.M` by `Mcongr`): here the carrier is the
generation state itself, so `dest` costs one application of the step map,
definitionally, independent of access path.

Implemented primarily by Claude Fable 5, refactored and commented by @kory33, 2026-07-09.
-/
import Mathlib.Data.PFunctor.Univariate.M

namespace PFunctor

/-- A pointed coalgebra: a carrier, a step map, and a current state.
    This is morally "the tree generated by unfolding `step` from `pt`",
    represented by its generation state rather than by the tree.

    Quantifying over carriers in `Type w` puts this one universe up. -/
structure UnfoldingMachine (P : PFunctor.{u, v}) : Type (max (max u v) (w + 1)) where
  S : Type w
  step : S → P.Obj S
  state : S

namespace UnfoldingMachine

variable {P : PFunctor}

/-- Root label. -/
def head (x : P.UnfoldingMachine) : P.A := (x.step x.state).1

/-- Subtree at branch `i`: same machine, advanced state. -/
def child (x : P.UnfoldingMachine) (i : P.B x.head) : P.UnfoldingMachine :=
  { x with state := (x.step x.state).2 i }

/-- One observation step, packaged as a `P.Obj` of unfoldings. -/
def destructure (x : P.UnfoldingMachine) : P.Obj P.UnfoldingMachine :=
  ⟨x.head, x.child⟩

/-- Unfolding machine's state type is hidden inside Σ, and the only data one could observe is
    the tree of labels produced by the unfolding.

    A natural thing to do is to *identify* two machines if one can never distinguish them by
    observing labels produced by them. This coinductive predicate captures this idea, and asserts that
    the root label of two unfolding machines are equal, and (coinductively) their evolutions
    also behave identically.

    In computer science, this relation is known as *bisimilarity*.
-/
coinductive EqBehavior : P.UnfoldingMachine → P.UnfoldingMachine → Prop
  | intro (x y : P.UnfoldingMachine)
      (a f g) (hx : x.destructure = ⟨a, f⟩) (hy : y.destructure = ⟨a, g⟩)
      (children_bisim : ∀ i, EqBehavior (f i) (g i)) :
      EqBehavior x y

theorem EqBehavior.refl (x : P.UnfoldingMachine) : EqBehavior x x :=
  EqBehavior.coinduct Eq
    (fun a _ h => h ▸ ⟨a.head, a.child, a.child, rfl, rfl, fun _ => rfl⟩) x x rfl

theorem EqBehavior.symm {x y : P.UnfoldingMachine} (h : EqBehavior x y) : EqBehavior y x :=
  EqBehavior.coinduct (fun a b => EqBehavior b a) (fun _ _ hba => by
    cases hba with | intro b a c f g hbf hag k => exact ⟨c, g, f, hag, hbf, k⟩) y x h

theorem EqBehavior.trans {x y z : P.UnfoldingMachine} (hxy : EqBehavior x y) (hyz : EqBehavior y z) :
    EqBehavior x z := by
  refine EqBehavior.coinduct (fun a c => ∃ b, EqBehavior a b ∧ EqBehavior b c) ?_ x z ⟨y, hxy, hyz⟩
  rintro a c ⟨b, h₁, h₂⟩
  cases h₁ with | intro a b a₁ f₁ g₁ ha₁ hb₁ k₁ =>
  cases h₂ with | intro b c a₂ f₂ g₂ hb₂ hc₂ k₂ =>
  cases hb₁.symm.trans hb₂
  exact ⟨a₁, f₁, g₂, ha₁, hc₂, fun i => ⟨g₁ i, k₁ i, k₂ i⟩⟩

instance setoid (P : PFunctor) : Setoid P.UnfoldingMachine :=
  ⟨EqBehavior, ⟨EqBehavior.refl, EqBehavior.symm, EqBehavior.trans⟩⟩

end UnfoldingMachine

/-- The M-type as a quotient: all unfoldings modulo bisimilarity.
Lives in `Type (max _ (w+1))`, at least one level above the coalgebra carriers. -/
def MQ (P : PFunctor) : Type _ := Quotient (UnfoldingMachine.setoid P)

namespace MQ

variable {P : PFunctor}

/-- Corecursion -/
def corec {S : Type v} (g : S → P.Obj S) (x : S) : P.MQ := ⟦⟨S, g, x⟩⟧

/-- Destructor: run the machine one step, re-package the successor states.
We lift the function which operates on particular state type. -/
def destructure : P.MQ → P.Obj P.MQ :=
  Quotient.lift (fun x => ⟨x.head, fun i => ⟦x.child i⟧⟩) <| fun x y hxy => by
    have hxy : UnfoldingMachine.EqBehavior x y := hxy
    cases hxy with | intro x y a f g hx hy k =>
    show P.map (⟦·⟧) x.destructure = P.map (⟦·⟧) y.destructure
    rw [hx, hy, PFunctor.map_eq, PFunctor.map_eq]
    exact congrArg _ (funext fun i => Quotient.sound (k i))

/-- `corec` is a coalgebra morphism. -/
@[simp] theorem dest_corec {X : Type v} (g : X → P.Obj X) (x : X) :
    (corec g x : P.MQ).destructure = P.map (corec g) (g x) := rfl

/-- `destructure` computes on `⟦·⟧`. -/
@[simp] theorem destructure_mk (x : P.UnfoldingMachine) :
    destructure ⟦x⟧ = P.map (⟦·⟧) x.destructure := rfl

/-- Coinduction: every dest-compatible relation is contained in equality.
This is where the quotient earns its keep over the bare (weakly terminal)
`UnfoldingMachine` type. -/
theorem bisim (R : P.MQ → P.MQ → Prop)
    (h : ∀ a b, R a b → ∃ a' f g,
      a.destructure = ⟨a', f⟩ ∧ b.destructure = ⟨a', g⟩ ∧ ∀ i, R (f i) (g i)) :
    ∀ a b, R a b → a = b := fun a b =>
  Quotient.inductionOn₂ a b fun p q hpq =>
    -- `destructure ⟦u⟧ ≡ P.map ⟦·⟧ u.destructure`, so `h` pulls back to a
    -- bisimulation on unfoldings; coinduction then gives `EqBehavior`.
    Quotient.sound <| UnfoldingMachine.EqBehavior.coinduct (fun u v => R ⟦u⟧ ⟦v⟧) (by
      intro u v huv
      obtain ⟨c, fq, gq, hu, hv, hfg⟩ := h _ _ huv
      rcases eu : u.destructure with ⟨ua, uf⟩
      rcases ev : v.destructure with ⟨va, vf⟩
      simp only [destructure_mk, eu, ev, PFunctor.map_eq] at hu hv
      cases hu; cases hv
      exact ⟨_, uf, vf, rfl, rfl, hfg⟩) p q hpq

/-- Uniqueness half of finality, against coalgebras with `Type v` carriers.
Together with `dest_corec`: `MQ` is "V-terminal" (Gylterud–Stenholm–Veltri);
no terminality in its own universe is claimed. -/
theorem corec_unique {X : Type v} (g : X → P.Obj X)
    (f : X → P.MQ) (f_homomorphic : ∀ x, (f x).destructure = P.map f (g x)) :
    f = corec g := by
  funext x₀
  refine bisim (fun a b => ∃ x, a = f x ∧ b = corec g x) ?_ _ _ ⟨x₀, rfl, rfl⟩
  rintro a b ⟨x, rfl, rfl⟩
  exact ⟨(g x).1, fun i => f ((g x).2 i), fun i => corec g ((g x).2 i),
    f_homomorphic x, rfl, fun i => ⟨(g x).2 i, rfl, rfl⟩⟩

/-! ### Essential smallness: `MQ.{u,u} P ≃ P.M`

Crossing to Mathlib's limit-constructed `P.M` (carriers at `Type u`).
This is the "replacement" step: the big quotient is equivalent to a small
type, because `P.M` itself is a small coalgebra through which every
unfolding factors. -/

section Small

variable {P : PFunctor}

/-- Fold the big quotient into the small `P.M`. -/
def toM : P.MQ → P.M := M.corec destructure

/-- Unfold `P.M`, viewed as a (small) coalgebra over itself. -/
def ofM : P.M → P.MQ := corec M.dest

/-- Terminal objects are unique: `toM ∘ ofM` and `id` are both coalgebra
morphisms `P.M → P.M`, so they agree by uniqueness of corecursion into the
terminal coalgebra `P.M`. -/
theorem toM_ofM (m : P.M) : toM (ofM m) = m :=
  congrFun ((M.corec_unique M.dest _ fun x => M.dest_corec destructure (ofM x)).trans
    (M.corec_unique M.dest id fun _ => rfl).symm) m

/-- The other round-trip needs genuine coinduction: the terminality argument
is unavailable here, because `MQ` is only terminal for coalgebras one
universe *below* itself — `corec destructure` on the carrier `MQ.{u,v,w}`
lands in `MQ.{u,v,max (w+1) u v}`, so `ofM ∘ toM` and `id` cannot both be
compared against it. -/
theorem ofM_toM (q : P.MQ) : ofM (toM q) = q := by
  refine bisim (fun a b => a = ofM (toM b)) ?_ _ _ rfl
  rintro _ b rfl
  exact ⟨b.destructure.1, fun i => ofM (toM (b.destructure.2 i)), b.destructure.2,
    congrArg (P.map ofM) (M.dest_corec destructure b), rfl, fun i => rfl⟩

/-- P.MQ is essentially small. -/
def equivM : P.MQ ≃ P.M where
  toFun := toM
  invFun := ofM
  left_inv := ofM_toM
  right_inv := toM_ofM

end Small

end MQ

end PFunctor
